os:
  - linux

dist:
  - xenial

compiler:
  - gcc
  - clang

language:
  - java
  - cpp

addons:
  apt:
    sources:
      - sourceline: deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8
        key_url: https://bazel.build/bazel-release.pub.gpg

before_install:
  - sudo apt-get update
  - sudo apt-get install bazel

script:
  - bazel build //...
  - bazel test //...