// Copyright 2019 David Johnston

#ifndef PHASICJ_TRACELOGGER_VECTOR_CLOCK_STORE_H_
#define PHASICJ_TRACELOGGER_VECTOR_CLOCK_STORE_H_

class vector_clock_store {

};

#endif //PHASICJ_TRACELOGGER_VECTOR_CLOCK_STORE_H_
