// Copyright 2019 David Johnston

#ifndef PHASICJ_TRACELOGGER_JVMTICONFIG_INITIALIZE_ENVIRONMENT_H_
#define PHASICJ_TRACELOGGER_JVMTICONFIG_INITIALIZE_ENVIRONMENT_H_

#include "jvmti.h"

void init(JVMTIEnv* jvmtiEnv);

#endif  // PHASICJ_TRACELOGGER_JVMTICONFIG_INITIALIZE_ENVIRONMENT_H_
